export interface AddUser {
  Role: string,
  Status: string,

  Id: number,
  UserId: string,
  UserProviderId: string,
  // Title: string,
  FirstName: string,
  // MiddleName: string,
  LastName: string,
  PracticeId: string,
  // PracticeName: string,
  // Degree: string,
  // Speciality: string,
  // SecondaryPpeciality: string,
  // PracticeRole: string,
  // DentalLicense: string,
  // ExpirationAt: string,
  // Active: boolean,
  // State: string,
  // NPI: string,
  // Dea: string,
  // Upin: string,
  // Nadean: string,
  // Ssn: string,
  // StreetAddress: string,
  // SuiteNumber: string,
  // PrimarPhone: string,
  // MobilePhone: string,
  Email: string,
  // AltEmail: string,
  // EncryptedPassword: string,
  // SelectedUserLocationIds: string
}
