import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-activepatient',
  templateUrl: './activepatient.component.html',
  styleUrls: ['./activepatient.component.scss']
})
export class ActivepatientComponent implements OnInit {

  pageSize: number = 50;
  page: number = 1;
  
  constructor() { }

  ngOnInit(): void {
  }
  public data = [{
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  },{
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": "Jethro",
    "Email": "Jethro@gmail.om",
    "PatientPortalAccount": "Butland",
    "Phone": "865982475",
    "Address": "Hyderabd",
    "Status" :"Active"
  }, {
    "Name": 49,
    "Email": "Lorenzo",
    "PatientPortalAccount": "Ranahan",
    "email": "lranahan1c@blogger.com",
    "Phone": "Male",
    "Address": "220.91.190.153"
  }, {
    "Name": 50,
    "Email": "Waldemar",
    "PatientPortalAccount": "Josephy",
    "email": "wjosephy1d@hp.com",
    "Phone": "Male",
    "Address": "44.68.137.28"
  }, {
    "Name": 51,
    "Email": "Jarvis",
    "PatientPortalAccount": "Schimmang",
    "email": "jschimmang1e@opera.com",
    "Phone": "Male",
    "Address": "94.2.156.13"
  }, {
    "Name": 52,
    "Email": "Madeline",
    "PatientPortalAccount": "Howlin",
    "email": "mhowlin1f@addtoany.com",
    "Phone": "Female",
    "Address": "0.117.14.53"
  }, {
    "Name": 53,
    "Email": "Izzy",
    "PatientPortalAccount": "Delacroux",
    "email": "Nameelacroux1g@nsw.gov.au",
    "Phone": "Male",
    "Address": "80.137.219.96"
  }, {
    "Name": 54,
    "Email": "Hendrika",
    "PatientPortalAccount": "Grevatt",
    "email": "hgrevatt1h@typepad.com",
    "Phone": "Female",
    "Address": "50.223.223.37"
  }, {
    "Name": 55,
    "Email": "Lindsey",
    "PatientPortalAccount": "Cunney",
    "email": "lcunney1i@icq.com",
    "Phone": "Female",
    "Address": "180.205.189.29"
  }, {
    "Name": 56,
    "Email": "Micky",
    "PatientPortalAccount": "Piaggia",
    "email": "mpiaggia1j@360.cn",
    "Phone": "Female",
    "Address": "56.165.195.118"
  }, {
    "Name": 57,
    "Email": "Jackqueline",
    "PatientPortalAccount": "Drache",
    "email": "jdrache1k@comsenz.com",
    "Phone": "Female",
    "Address": "22.14.20.120"
  }, {
    "Name": 58,
    "Email": "Jeromy",
    "PatientPortalAccount": "Goulter",
    "email": "jgoulter1l@usatoday.com",
    "Phone": "Male",
    "Address": "49.39.163.192"
  }, {
    "Name": 59,
    "Email": "Farrand",
    "PatientPortalAccount": "BroadbrNamege",
    "email": "fbroadbrNamege1m@cnn.com",
    "Phone": "Female",
    "Address": "210.219.27.199"
  }, {
    "Name": 60,
    "Email": "Alisa",
    "PatientPortalAccount": "Sans",
    "email": "asans1n@1und1.de",
    "Phone": "Female",
    "Address": "37.55.227.130"
  }, {
    "Name": 61,
    "Email": "Bessy",
    "PatientPortalAccount": "Matyas",
    "email": "bmatyas1o@plala.or.jp",
    "Phone": "Female",
    "Address": "21.84.47.246"
  }, {
    "Name": 62,
    "Email": "Gratiana",
    "PatientPortalAccount": "Mealand",
    "email": "gmealand1p@mayoclinic.com",
    "Phone": "Female",
    "Address": "78.189.144.156"
  }, {
    "Name": 63,
    "Email": "Merwyn",
    "PatientPortalAccount": "Kinnen",
    "email": "mkinnen1q@cdc.gov",
    "Phone": "Male",
    "Address": "30.232.202.9"
  }, {
    "Name": 64,
    "Email": "Granny",
    "PatientPortalAccount": "Ganny",
    "email": "gganny1r@comcast.net",
    "Phone": "Male",
    "Address": "136.146.4.30"
  }, {
    "Name": 65,
    "Email": "Nataline",
    "PatientPortalAccount": "Rauprich",
    "email": "nrauprich1s@dmoz.org",
    "Phone": "Female",
    "Address": "48.54.218.242"
  }, {
    "Name": 66,
    "Email": "Hyacinthie",
    "PatientPortalAccount": "Gothrup",
    "email": "hgothrup1t@cam.ac.uk",
    "Phone": "Female",
    "Address": "34.164.172.19"
  }, {
    "Name": 67,
    "Email": "Cherrita",
    "PatientPortalAccount": "Dumigan",
    "email": "cdumigan1u@gravatar.com",
    "Phone": "Female",
    "Address": "102.42.218.45"
  }, {
    "Name": 68,
    "Email": "Jarrod",
    "PatientPortalAccount": "Pabelik",
    "email": "jpabelik1v@dailymail.co.uk",
    "Phone": "Male",
    "Address": "223.27.100.245"
  }, {
    "Name": 69,
    "Email": "Tersina",
    "PatientPortalAccount": "Benion",
    "email": "tbenion1w@ucla.edu",
    "Phone": "Female",
    "Address": "69.180.188.57"
  }, {
    "Name": 70,
    "Email": "Nancy",
    "PatientPortalAccount": "Pallister",
    "email": "npallister1x@opensource.org",
    "Phone": "Female",
    "Address": "221.22.210.236"
  }, {
    "Name": 71,
    "Email": "Addie",
    "PatientPortalAccount": "Whiteson",
    "email": "awhiteson1y@stumbleupon.com",
    "Phone": "Male",
    "Address": "79.93.211.55"
  }, {
    "Name": 72,
    "Email": "Reta",
    "PatientPortalAccount": "Pashbee",
    "email": "rpashbee1z@disqus.com",
    "Phone": "Female",
    "Address": "73.20.198.120"
  }, {
    "Name": 73,
    "Email": "Tova",
    "PatientPortalAccount": "Strathearn",
    "email": "tstrathearn20@godaddy.com",
    "Phone": "Female",
    "Address": "162.181.226.254"
  }, {
    "Name": 74,
    "Email": "Elle",
    "PatientPortalAccount": "Strute",
    "email": "estrute21@intel.com",
    "Phone": "Female",
    "Address": "139.174.201.163"
  }, {
    "Name": 75,
    "Email": "Janelle",
    "PatientPortalAccount": "Herrero",
    "email": "jherrero22@webnode.com",
    "Phone": "Female",
    "Address": "114.113.144.38"
  }, {
    "Name": 76,
    "Email": "Gena",
    "PatientPortalAccount": "Sproule",
    "email": "gsproule23@ycombinator.com",
    "Phone": "Female",
    "Address": "184.126.143.180"
  }, {
    "Name": 77,
    "Email": "Gothart",
    "PatientPortalAccount": "Schiementz",
    "email": "gschiementz24@state.tx.us",
    "Phone": "Male",
    "Address": "213.71.18.49"
  }, {
    "Name": 78,
    "Email": "SNameoney",
    "PatientPortalAccount": "Rutherforth",
    "email": "srutherforth25@yolasite.com",
    "Phone": "Female",
    "Address": "243.163.212.137"
  }, {
    "Name": 79,
    "Email": "Bevon",
    "PatientPortalAccount": "Welsby",
    "email": "bwelsby26@foxnews.com",
    "Phone": "Male",
    "Address": "89.50.241.29"
  }, {
    "Name": 80,
    "Email": "Deina",
    "PatientPortalAccount": "Bignal",
    "email": "dbignal27@dropbox.com",
    "Phone": "Female",
    "Address": "212.10.202.97"
  }, {
    "Name": 81,
    "Email": "Hermy",
    "PatientPortalAccount": "Sesser",
    "email": "hsesser28@hud.gov",
    "Phone": "Male",
    "Address": "114.6.37.36"
  }, {
    "Name": 82,
    "Email": "Rebecca",
    "PatientPortalAccount": "Shallcrass",
    "email": "rshallcrass29@yellowpages.com",
    "Phone": "Female",
    "Address": "86.186.159.154"
  }, {
    "Name": 83,
    "Email": "Moria",
    "PatientPortalAccount": "Cochern",
    "email": "mcochern2a@reddit.com",
    "Phone": "Female",
    "Address": "6.193.12.145"
  }, {
    "Name": 84,
    "Email": "Giacopo",
    "PatientPortalAccount": "Bernuzzi",
    "email": "gbernuzzi2b@goodreads.com",
    "Phone": "Male",
    "Address": "60.136.83.153"
  }, {
    "Name": 85,
    "Email": "Parnell",
    "PatientPortalAccount": "Ransfield",
    "email": "pransfield2c@sphinn.com",
    "Phone": "Male",
    "Address": "207.183.178.209"
  }, {
    "Name": 86,
    "Email": "Sterne",
    "PatientPortalAccount": "Brandrick",
    "email": "sbrandrick2d@quantcast.com",
    "Phone": "Male",
    "Address": "194.222.233.52"
  }, {
    "Name": 87,
    "Email": "Alastair",
    "PatientPortalAccount": "Droghan",
    "email": "adroghan2e@census.gov",
    "Phone": "Male",
    "Address": "122.54.170.153"
  }, {
    "Name": 88,
    "Email": "Darsie",
    "PatientPortalAccount": "Egdal",
    "email": "degdal2f@economist.com",
    "Phone": "Female",
    "Address": "39.71.149.75"
  }, {
    "Name": 89,
    "Email": "Jyoti",
    "PatientPortalAccount": "Shemilt",
    "email": "jshemilt2g@fastcompany.com",
    "Phone": "Female",
    "Address": "206.82.56.137"
  }, {
    "Name": 90,
    "Email": "Sylvia",
    "PatientPortalAccount": "Weinmann",
    "email": "sweinmann2h@w3.org",
    "Phone": "Female",
    "Address": "190.154.233.33"
  }, {
    "Name": 91,
    "Email": "Hube",
    "PatientPortalAccount": "Burds",
    "email": "hburds2i@google.it",
    "Phone": "Male",
    "Address": "25.189.44.22"
  }, {
    "Name": 92,
    "Email": "Sue",
    "PatientPortalAccount": "Mutch",
    "email": "smutch2j@shareasale.com",
    "Phone": "Female",
    "Address": "250.107.249.212"
  }, {
    "Name": 93,
    "Email": "Laurie",
    "PatientPortalAccount": "Giacomucci",
    "email": "lgiacomucci2k@jalbum.net",
    "Phone": "Male",
    "Address": "207.146.21.177"
  }, {
    "Name": 94,
    "Email": "Aigneis",
    "PatientPortalAccount": "Hazeltine",
    "email": "ahazeltine2l@ycombinator.com",
    "Phone": "Female",
    "Address": "195.214.255.180"
  }, {
    "Name": 95,
    "Email": "Nolana",
    "PatientPortalAccount": "Pilkington",
    "email": "npilkington2m@cyberchimps.com",
    "Phone": "Female",
    "Address": "99.178.205.28"
  }, {
    "Name": 96,
    "Email": "Margalit",
    "PatientPortalAccount": "Norsister",
    "email": "mnorsister2n@discovery.com",
    "Phone": "Female",
    "Address": "93.173.70.126"
  }, {
    "Name": 97,
    "Email": "Audrie",
    "PatientPortalAccount": "Janczyk",
    "email": "ajanczyk2o@simplemachines.org",
    "Phone": "Female",
    "Address": "121.69.119.102"
  }, {
    "Name": 98,
    "Email": "Annmarie",
    "PatientPortalAccount": "Humburton",
    "email": "ahumburton2p@biglobe.ne.jp",
    "Phone": "Female",
    "Address": "202.108.4.73"
  }, {
    "Name": 99,
    "Email": "Patience",
    "PatientPortalAccount": "Ruslen",
    "email": "pruslen2q@ebay.co.uk",
    "Phone": "Female",
    "Address": "177.187.143.236"
  }, {
    "Name": 100,
    "Email": "Virgie",
    "PatientPortalAccount": "Sagg",
    "email": "vsagg2r@blog.com",
    "Phone": "Female",
    "Address": "193.134.165.63"
  }];
  
  SearchKey = "";
  SearchDetails() {
    debugger;
    this.data=this.data.filter((invoice) => this.isMatch(invoice));
  }

  isMatch(item) {
    debugger;
    if (item instanceof Object) {
      return Object.keys(item).some((k) => this.isMatch(item[k]));
    } else {
      return item == null?'':item.toString().indexOf(this.SearchKey) > -1
    }
  }
  }
  

